- hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: webserver
      image: efreet05/hello:10.1
      state: started
      ports:
      - "80:8080"

